---
- block:
    - name: install redis-server package
      ansible.builtin.apt:
        name: "redis-server"
        state: present
    - name: setup redis-server connection password
      ansible.builtin.lineinfile:
        path: "/etc/redis/redis.conf"
        regexp: "^# requirepass "
        line: "requirepass {{ redis_pass }}"
        backup: yes
      when: redis_pass
      notify: restart redis-server
  tags:
    - redis
